apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kargo-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.controller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kargo.selectorLabels" . | nindent 6 }}
      {{- include "kargo.controller.labels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: metrics
