name: Release

on:
  release:
    types: 
    - published
  push:
    branches:
      - test-metrics
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-charts:
    permissions:
      contents: read
      packages: write # Used to push images to `ghcr.io`
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
      with:
        egress-policy: audit

    - name: Determine which repository to use
      id: chart_repo
      run: |
        REPO=ghcr.io/sergio91pt/kargo-charts
        if ${{ github.event_name != 'release' }}
        then
        REPO=ghcr.io/sergio91pt/kargo-charts-unstable
        fi
        echo "Repository is set to: $REPO"
        echo "chart_repo=$REPO" >> $GITHUB_OUTPUT
    - name: Determine Version
      id: version
      run: |
        VERSION=${{ github.ref_name }}
        if ${{ github.event_name != 'release' }}
        then
        VERSION=0.0.1-unstable-${{ github.sha }}
        fi
        echo "VERSION is set to: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Set up Helm
      uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      with:
        version: '3.19.4'
    - name: Login to GHCR
      uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Publish chart
      env:
        HELM_EXPERIMENTAL_OCI: '1'
        KARGO_CHARTS_REPO: ${{ steps.chart_repo.outputs.chart_repo }}
        VERSION: ${{ steps.version.outputs.version }}
      run: |
        CHART_VERSION=$(echo $VERSION | cut -c 2-)
        cd charts/kargo
        helm dep up
        helm package . --version ${CHART_VERSION} --app-version ${VERSION}
        helm push kargo-${CHART_VERSION}.tgz oci://${KARGO_CHARTS_REPO}
